version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        #ports:
        #    - 8765:80
        volumes:
            - /home/administrator/speedtest/data:/config
        environment:
            - TZ=America/New_York
            - PGID=100
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.speedtest.entrypoints=http"
            - "traefik.http.routers.speedtest.rule=Host(`speedtest.local.thedrainvilles.xyz`)"
            - "traefik.http.middlewares.speedtest-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.speedtest.middlewares=speedtest-https-redirect"
            - "traefik.http.routers.speedtest-secure.entrypoints=https"
            - "traefik.http.routers.speedtest-secure.rule=Host(`speedtest.local.thedrainvilles.xyz`)"
            - "traefik.http.routers.speedtest-secure.tls=true"
            - "traefik.http.routers.speedtest-secure.service=speedtest"
            - "traefik.http.services.speedtest.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy"

networks:
    proxy:
        external: true