version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25565:25565"
    env_file:
        - /docker/minecraft/minecraft.env
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /docker/minecraft/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro