version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: "0 0 1 * * *" 
      TZ: America/New_York 
      WATCHTOWER_CLEANUP: "true" 
      WATCHTOWER_DEBUG: "true"      
      #WATCHTOWER_NOTIFICATIONS: "email" 
      #WATCHTOWER_NOTIFICATION_EMAIL_FROM: "cldocker01@cloud.local"
      #WATCHTOWER_NOTIFICATION_EMAIL_TO: "pushover@mailrise.xyz" 
      # you have to use a network alias here, if you use your own certificate 
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "10.1.149.19" 
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "8025" 
      #WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2   
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.watchtower.entrypoints=http"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.local.thedrainvilles.xyz`)"
      - "traefik.http.middlewares.watchtower-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.watchtower.middlewares=watchtower-https-redirect"
      - "traefik.http.routers.watchtower-secure.entrypoints=https"
      - "traefik.http.routers.watchtower-secure.rule=Host(`watchtower.local.thedrainvilles.xyz`)"
      - "traefik.http.routers.watchtower-secure.tls=true"
      - "traefik.http.routers.watchtower-secure.service=watchtower"
      - "traefik.http.services.watchtower.loadbalancer.server.port=3080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true