version: '3'

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/administrator/uptimekuma/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.entrypoints=http"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.local.thedrainvilles.xyz`)"
      - "traefik.http.middlewares.uptimekuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uptimekuma.middlewares=uptimekuma-https-redirect"
      - "traefik.http.routers.uptimekuma-secure.entrypoints=https"
      - "traefik.http.routers.uptimekuma-secure.rule=Host(`uptimekuma.local.thedrainvilles.xyz`)"
      - "traefik.http.routers.uptimekuma-secure.tls=true"
      - "traefik.http.routers.uptimekuma-secure.service=uptimekuma"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true