version: '3'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- TRANSMISSION_WEB_HOME= #optional
      - USER=admin #optional
      - PASS=N3trunner! #optional
      #- WHITELIST=iplist #optional
      #- PEERPORT=peerport #optional
      #- "HOST_WHITELIST=dnsname list" #optional
    volumes:
      - /home/administrator/transmission/data:/config
      - /home/administrator/media:/downloads
      - /home/administrator/transmission/watch:/watch
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local.thedrainvilles.xyz`)"
      - "traefik.http.middlewares.transmission-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.transmission.middlewares=transmission-https-redirect"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.rule=Host(`transmission.local.thedrainvilles.xyz`)"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      #- "traefik.http.services.transmission.loadbalancer.server.port=51413"
      #- "traefik.http.services.transmission.loadbalancer.server.port=51413/udp"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true